server:
  port: 8100

dubbo:
  application:
    name: shop-center-server

  registry:
    protocol: zookeeper
    address: 152.136.145.182
    port: 2181
    timeout: 30000
  consumer:
    timeout: 30000
    retries: 3
  provider:
    retries: 3
    timeout: 30000

spring:
  application:
    name: shop-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shop_center?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 1998yang
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #最初大小
      initial-size: 1
      #最小链接数
      min-idle: 1
      #最大连接数
      max-active: 5
      #获取链接 最大等待时间 超过就超时
      max-wait: 30000
      #多久进行一次检查 检查需要关闭的空闲链接
      time-between-eviction-runs-millis: 600000
      #一个链接在 连接池中 最小生存时间
      min-evictable-idle-time-millis: 300000
      # 设置从连接池获取连接时是否检查连接有效性，true时，每次都检查;false时，不检查
      test-on-borrow: true
      #设置往连接池归还连接时是否检查连接有效性，true时，每次都检查;false时，不检查
      test-on-return: true
      # 设置从连接池获取连接时是否检查连接有效性，true时，如果连接空闲时间超过min-evictable-idle-time-millis进行检查，否则不检查;false时，不检查
      test-while-idle: true
      # 检验连接是否有效的查询语句。如果数据库Driver支持ping()方法，则优先使用ping()方法进行检查，否则使用validationQuery查询进行检查。(Oracle jdbc Driver目前不支持ping方法)
      validation-query: select 1 from dual
      #长连接
      keep-alive: true
      #回收不活跃链接
      remove-abandoned: true
      #超时链接回收 秒
      remove-abandoned-timeout: 60
      #回收时打印日志
      log-abandoned: true
      #缓存游标 打开PSCache，并且指定每个连接上PSCache的大小，Oracle等支持游标的数据库，打开此开关，会以数量级提升性能，具体查阅PSCache相关资料
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  security:
    user:
      name: yangweiye
      password: 1998yang

rocketmq:
  name-server: 152.136.145.182:9876